name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Run CMake with Ninja'
      run: |
        apt install -y cmake ninja-build
        mkdir -p ${{ runner.workspace }}/build
        cd '${{ runner.workspace }}/build' && cmake -GNinja ..
        ninja -C '${{ runner.workspace }}/build'
    - name: Run tests
      run: ninja -C '${{ runner.workspace }}/build' test
