name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Run CMake with Ninja'
      run: |
        mkdir -p ${{ runner.workspace }}/build
        cd '${{ runner.workspace }}/build' && cmake ..
        make -C '${{ runner.workspace }}/build' -j`nproc`
    - name: Run tests
      run: make -C '${{ runner.workspace }}/build' test
