name: clang-format checks
on: [pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: wolletd/clang-format-checker@v1
        with:
          target-ref: "${{ github.base_ref }}"
